name: Build LaTeX documents
on: [push]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      
      - name: Install TinyTeX
        uses: r-lib/actions/setup-tinytex@v2
        env:
          TINYTEX_INSTALLER: TinyTeX
      
      - name: Install LaTeX packages
        run: |
          tlmgr install amsmath
          tlmgr install physics
          tlmgr install mathtools
          tlmgr install cancel
          tlmgr install siunitx
          tlmgr install graphics
          tlmgr install xcolor
      
      - name: Find TeX files
        id: find_tex
        run: |
          echo "TEX_FILES<<EOF" >> $GITHUB_ENV
          find . -name "*.tex" | sed 's|^\./||' >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      
      - name: Compile LaTeX documents
        run: |
          mkdir -p pdfs
          for file in ${{ env.TEX_FILES }}; do
            echo "Compiling $file"
            directory=$(dirname "$file")
            filename=$(basename "$file" .tex)
            pdflatex -interaction=nonstopmode -output-directory="$directory" "$file" || true
            pdflatex -interaction=nonstopmode -output-directory="$directory" "$file" || true
            # Move the generated PDF to the pdfs directory
            if [ -f "$directory/$filename.pdf" ]; then
              mkdir -p "pdfs/$directory"
              cp "$directory/$filename.pdf" "pdfs/$directory/$filename.pdf"
            fi
          done
      
      - name: Commit and push PDFs
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add pdfs/
          git commit -m "Update compiled PDFs" || echo "No changes to commit"
          git push